# Generated by Django 2.1.1 on 2018-09-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('note_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('color', models.CharField(max_length=8)),
                ('created', models.DateTimeField()),
                ('last_edited', models.DateTimeField()),
            ],
        ),
    ]
