# Generated by Django 2.1.1 on 2018-10-04 17:40

from django.db import migrations, models
import xncore.xauth


class Migration(migrations.Migration):

    dependencies = [
        ('xnotesapp', '0007_auto_20181004_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default=xncore.xauth.gen_salt, max_length=15),
        ),
    ]
