# Generated by Django 2.1.1 on 2018-10-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnotesapp', '0008_auto_20181004_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=200)),
            ],
        ),
    ]
